### ISSUE TITLE
MCPで集計を行う方法について

### ISSUE THREAD

**Issue by kawa-** [Kanatoko/MCP#1]
こんにちは、私も、「しかしこのようなアプローチには大きな欠点があります。それはCPUリソースを1コア分しか消費できないということ」という問題に直面しており、MCPにたどり着きました。

ExampleにあるUpperCase.javaを動かすことは出来たのですが、以下のワンライナーの集計のようなことをMCPにするには、どのように書けばよいでしょうか？

```
#1〜100まで足し合わせる
$ seq 100 | awk '{s+=$1}END{printf "%.0f\n", s}'
5050
```

**Comment by Kanatoko** [comment]
seq 100 | java -cp output/mcp.jar net.jumperz.app.MCP.MCP net.jumperz.io.multicore.example.MSum

みたいな感じで集計するサンプルを作ってみました。入力データのサイズが大きい場合にはawkより速いと思います。

staticな変数に合計値を保持しておき、各スレッドからその変数の値を変更していきます。プロセスのシャットダウン時に標準出力に出力させています。

MCPの開発では、集計系の処理を行うイメージは、持っていませんでした。そのため、プロセスのシャットダウンをフックするというややトリッキーなアプローチになっています。

**Comment by kawa-** [comment]
ありがとうございます。帰宅したら動かしてみます！

**Comment by kawa-** [comment]
だいぶ日が空いてしまいましたが、さきほど試してみました、結論から言うと2 coresを使うときにawkを上回りました！
- Opteron 3280 (8 cores)
- Linux Kernal 3.8.0-44

という環境で、

```
$ seq -f %.0f 100000000 > 100M.data

$  time cat 100M.data | awk '{s+=$1}END{printf "%.0f\n", s}'
5000000050000000

real    0m34.458s
user    0m33.432s
sys 0m8.536s

$ time cat 100M.data | perl -e '$sum = 0; while (<>) { $sum += $_; } print $sum'
5000000050000000
real    0m24.762s
user    0m24.036s
sys 0m5.712s

$ time cat 100M.data | java -cp output/mcp.jar net.jumperz.app.MCP.MCP --thread-count 2 net.jumperz.io.multicore.example.MSum
5000000050000000

real    0m17.381s
user    0m30.240s
sys 0m5.396s
```

となり、MCPが最速です。ただ、並列度が4、8にしたときは処理速度の低下が見られました。

```
$ time cat 100M.data | java -cp output/mcp.jar net.jumperz.app.MCP.MCP --thread-count 4 net.jumperz.io.multicore.example.MSum
5000000050000000

real    0m52.105s
user    3m6.000s
sys 0m8.828s

$ time cat 100M.data | java -cp output/mcp.jar net.jumperz.app.MCP.MCP --thread-count 8 net.jumperz.io.multicore.example.MSum
5000000050000000

real    1m45.603s
user    8m14.888s
sys 0m26.816s
```

**Comment by Kanatoko** [comment]
ご連絡ありがとうございます。
とりあえずcloseしておきますね。また何かあればお気軽にお願いします。

**Comment by kawa-** [comment]
素晴らしいフレームワーク、ありがとうございました！
